### ISSUE TITLE
it crashes on first use

### ISSUE THREAD

**Issue by sils** [mhallin/cov-exclude-py#1]
Hi, neat thing. We're looking for using it for the coala project (coala-analyzer.org) but whenever I run it I do get an exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/pytest.py", line 17, in <module>
    raise SystemExit(pytest.main())
  File "/usr/lib/python3.5/site-packages/_pytest/config.py", line 48, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python3.5/site-packages/_pytest/main.py", line 115, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python3.5/site-packages/_pytest/main.py", line 110, in wrap_session
    exitstatus=session.exitstatus)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/lib/python3.5/site-packages/_pytest/terminal.py", line 361, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/usr/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python3.5/site-packages/pytest_cov/plugin.py", line 160, in pytest_sessionfinish
    self.cov_controller.finish()
  File "/usr/lib/python3.5/site-packages/pytest_cov/engine.py", line 141, in finish
    self.cov.stop()
  File "/usr/lib/python3.5/site-packages/coverage/control.py", line 692, in stop
    self.collector.stop()
  File "/usr/lib/python3.5/site-packages/coverage/collector.py", line 277, in stop
    "Expected current collector to be %r, but it's %r" % (self, self._collectors[-1])
AssertionError: Expected current collector to be <Collector at 0x7faa43ede470: CTracer>, but it's <Collector at 0x7faa3a6d6d68: CTracer>
```

I'm running it with this config:

```
[pytest]
norecursedirs =
    .git
    dist
    build
    venv
    .env
testpaths =
    coalib
    bears
    docs
python_files = *Test.py
python_classes = *Test
python_functions = *_test
timeout = 25
addopts =
    --cov
    --color=yes
    --doctest-glob=*.rst
    --ignore=coalib/tests/collecting/collectors_test_dir/bears/incorrect_bear.py

[coverage:run]
branch = True
cover_pylib = False
source =
    coalib
    bears
omit = */tests/*

[coverage:report]
show_missing = True

[coverage:html]
directory = .htmlreport
```

**Comment by mhallin** [comment]
Strange. It might be some interaction with the regular Coverage plugin. Could you please try disabling that and see what happens?

As an aside, I don't know the usefulness of coverage reports together with this plugin as it disables a lot of tests.

**Comment by sils** [comment]
Oh then I got this wrong, I actually thought this plugin would rely on coverage being active and interpolate the correct coverage then since it measures the coverage anyway implicitly?

**Comment by mhallin** [comment]
While it uses the same underlying Python library (https://bitbucket.org/ned/coveragepy) as the coverage plugin, there are some slight differences. For example, the standard coverage plugin only needs to activate its recording once at the start, and then once at the end. This plugin records the test collection phase and then each test individually to determine code paths used by each test.

I think the fix here might be to add a better error message when it's used together with the Pytest coverage plugin :-)

**Comment by sils** [comment]
Is there no possibility to make the combination work - or rather simply show the coverage through your plugin in the end?

**Comment by mhallin** [comment]
I suppose I could add a flag to print out something at the end of the test run, but I'm still not sure if the data would be meaningful. The point of this plugin is to deselect a large number of tests, meaning that the code coverage will be very low.

**Comment by sils** [comment]
Well but you deselect the tests based on the knowledge of the coverage - so you can join the coverage from the deselected tests (which you know) with the one from the run, right?
